# appveyor.yml
---
environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

build: off

install:
- pip install tox

before_test:
- ps: tests/test_setup_adds.ps1

test_script:
- ps: tests/test_setup_adcs.ps1
